"""fix alembic useng error

Revision ID: 0f6bb09dd310
Revises: 
Create Date: 2023-05-20 23:29:09.825659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6bb09dd310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_col', sa.UUID(), nullable=False, comment='Первичный Ключ'),
    sa.Column('test_name', sa.String(), nullable=True, comment='Test name'),
    sa.Column('url', sa.String(), nullable=True, comment='url'),
    sa.PrimaryKeyConstraint('test_col')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
